### ISSUE TITLE
[Initial] Define API Endpoints

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/UA1303#62]
**Objective**: To establish the API endpoints that will be used for the application's core functionality.

**Sub-Tasks**:
1. **List Down Required Endpoints**:
   - Based on the project requirements, list down the necessary API endpoints, such as `/startups`, `/investors`, `/projects`, `/messages`, etc.

2. **Define Endpoint Methods**:
   - For each endpoint, define the HTTP methods (GET, POST, PUT, DELETE) and their purpose.

3. **Create API Documentation**:
   - Document the endpoints, including their URL patterns, request/response formats, and parameters. Tools like Swagger can be used.

4. **Develop Endpoints in Django**:
   - Start implementing the endpoints using Django Rest Framework (DRF). This includes defining serializers, viewsets, and routing.

5. **Test Endpoints**:
   - Use tools like Postman or unit tests to ensure each endpoint behaves as expected.

**Comment by SergeKry** [comment]
can be solved by integrating swagger.
source: discord. 12-Dec
