### ISSUE TITLE
[Initial] Design the Database Schema

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/UA1303#74]
**Objective**: To create a well-structured database schema that efficiently supports the application's data requirements.

**Sub-Tasks**:
1. **Identify Entities and Relationships**:
   - Analyze the project requirements to identify key entities such as startups, investors, profiles, projects, messages, etc.
   - Determine the relationships between these entities (one-to-many, many-to-many, etc.).

2. **Define Entity Attributes**:
   - List down the attributes for each entity, like startup name, investor details, project descriptions, contact information, etc.

3. **Create ER Diagrams**:
   - Use a database modeling tool to create Entity-Relationship (ER) diagrams representing the structure of the database.

4. **Normalize Database**:
   - Ensure the database design adheres to normalization rules to reduce redundancy and improve data integrity.

5. **Review and Iterate**:
   - Review the schema with the team and iterate based on feedback.

**Comment by SergeKry** [comment]
Proposed solution
![Image](https://github.com/user-attachments/assets/429b1f09-7047-47d2-bf5f-e81c10205413)
